org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.238
loader_version_range=[1,)

create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
junit_version=5.11.4

mod_id=createprobabilitytuning
mod_name=Create Probability Tuning
mod_version=1.0.0
mod_group_id=com.pycoder.createprobabilitytuning
mod_authors=Pycoder
mod_description=Create Probability Tuning NeoForge mod for Minecraft 1.21.1.
mod_license=All Rights Reserved
